---

# Install OpenSSL
- name: Install OpenSSL packages
  ansible.builtin.package:
    name: "{{ openssl_packages }}"
    state: present
  become: yes

- name: Defined pip version to use
  ansible.builtin.set_fact:
    __pip_executable: "pip{{ ansible_facts['python']['version']['major'] }}"

- name: Get installed pypi packages
  community.general.pip_package_info:
    clients:
      - "{{ __pip_executable }}"
  register: __pip
  become: yes

- name: Install cryptography
  ansible.builtin.package:
    name: "{{ openssl_cryptography_packages }}"
    state: present
  become: yes
  when: __pip['packages'][__pip_executable]['cryptography'] is undefined

- name: Create directory structure
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode }}"
  become: yes
  loop: "{{ openssl_dirs }}"
  tags: molecule-idempotence-notest

# - name: Flip base_run boolean so it won't be run multiple times
#   ansible.builtin.set_fact:
#     base_run: false
