---

# Install OpenSSL
- name: Install OpenSSL packages
  ansible.builtin.package:
    name: "{{ openssl_packages }}"
    state: present
  become: yes
  when: openssl_packages | default([]) | length > 0

- name: Get installed pypi packages
  community.general.pip_package_info:
    clients:
      - "{{ openssl_pip_executable }}"
  register: __pip
  become: yes
  when: openssl_pip_executable | length > 0

- name: Install cryptography
  ansible.builtin.package:
    name: "{{ openssl_cryptography_packages }}"
    state: present
  become: yes
  when:
    - openssl_pip_executable | length > 0
    - __pip['packages'][openssl_pip_executable]['cryptography'] is undefined

- name: Create directory structure
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode }}"
  become: yes
  loop: "{{ openssl_dirs }}"
  tags: molecule-idempotence-notest

# - name: Flip base_run boolean so it won't be run multiple times
#   ansible.builtin.set_fact:
#     base_run: false
