---

# Install OpenSSL
- name: Install OpenSSL packages
  packages:
    name: "{{ openssl_packages }}"
    state: present

# Possible types : docker (ca+server+client), self-signed, ca, server, client
- include_tasks: "{{ openssl_type }}.yml"
