---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Perform installation phase
  ansible.builtin.include_tasks: install.yml

# Possible types : docker (ca + server + client), self-signed, ca, server, client
- name: Include tasks
  ansible.builtin.include_tasks: "{{ openssl_type }}.yml"
  when: openssl_type is defined and openssl_type | length > 0
