---

# Install OpenSSL
- name: Install OpenSSL packages
  ansible.builtin.package:
    name: "{{ openssl_packages }}"
    state: present

# Possible types : docker (ca + server + client), self-signed, ca, server, client
- name: Include tasks
  ansible.builtin.include_tasks: "{{ openssl_type }}.yml"
  when: openssl_type is defined and openssl_type | length > 0
