---

# - name: Perform base actions
#   ansible.builtin.include_tasks: base.yml
#   when: base_run is undefined or not base_run | bool

- name: Generate private key (server)
  community.crypto.openssl_privatekey:
    path: "{{ openssl_server_key }}"
    mode: "0600"
    backup: yes

- name: Generate certificate signing request
  community.crypto.openssl_csr:
    path: "{{ openssl_server_csr }}"
    privatekey_path: "{{ openssl_server_key }}"
    common_name: "{{ openssl_fqdn }}"
    subject_alt_name: "{{ ['DNS:' + openssl_fqdn] + (openssl_fqdn_additional | map('regex_replace', '^', 'DNS:') | list) }}"
    mode: "0600"
    backup: yes

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "{{ openssl_server_crt }}"
    privatekey_path: "{{ openssl_server_key }}"
    csr_path: "{{ openssl_server_csr }}"
    provider: selfsigned
    mode: "0644"
    backup: yes
