---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    python38: False
    python39: False
    openssl_fqdn: server.example.com
    openssl_fqdn_additional: ['vhost1.example.com', 'vhost2.example.com']
  pre_tasks:
    - name: Create 'remote_tmp'
      ansible.builtin.file:
        path: /root/.ansible/tmp
        state: directory
        mode: "0700"
    - name: Show python information
      ansible.builtin.debug:
        msg:
          "ansible_python_version": "{{ ansible_python_version }}"
          "ansible_python_executable": "{{ ansible_python['executable'] }}"
  roles:
    - python
  tasks:
    - name: Include role 'ansible-role-openssl'
      ansible.builtin.include_role:
        name: ansible-role-openssl
