---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    python38: False
    python39: False
    openssl_fqdn: server.example.com
    openssl_fqdn_additional: ['vhost1.example.com', 'vhost2.example.com']
  roles:
    - deitkrachten.python
  tasks:
    - name: Include role 'ansible-role-openssl'
      ansible.builtin.include_role:
        name: ansible-role-openssl
