---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ln -fs molecule/default/requirements.yml
  ansible-lint
  rm -f requirements.yml
platforms:

  - name: openssl-alpine3-node1
    image: "robertdebock/alpine:latest"
    rhsm: False
    command: ${MOLECULE_DOCKER_COMMAND:-""}

    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro


    privileged: True
    pre_build_image: False
    dockerfile: Dockerfile.alpine3.j2

provisioner:
  name: ansible

  env:
    ANSIBLE_PIPELINING: "True"
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    group_vars: {}
    host_vars: {}
scenario:
  name: default
verifier:
  name: ansible
